### ISSUE TITLE
Snap network-manager raises error of missing libnetplan.so.1 when creating connection in Ubuntu Core 24

### ISSUE THREAD

**Issue by zhanggyb** [snapcore/network-manager-snap#42]
Hello,

We met this issue when testing Ubuntu Core 24 on a IoT device:

When trying to create a connection using `nmcli` in the `network-manager` snap, it will raise an Error showing failed to add connection but actually the wwan connection is successfully created.

System journal shows that `libnetplan.so.1` is missing.

To reproduce, download and install pre-built Ubuntu Core 24 (e.g. [core-24-amd64](https://cdimage.ubuntu.com/ubuntu-core/24/stable/current/ubuntu-core-24-amd64.img.xz)) from https://ubuntu.com/core/docs/supported-platforms.

Try to create a ethernet connection, for example:

```
nmcli connection add type ethernet con-name "staticCon" ifname enp46s0 ipv4.method manual ipv4.addresses 192.168.1.100/24 ipv4.gateway 192.168.1.1
```

The command will returns with failure. See attached screenshots for details.

We tried the `network-manager` snap in the edge channel but it still can be reproduced.

![create-ethernet-fail](https://github.com/user-attachments/assets/8f58697f-e007-46dc-af97-dcd727a00ae6)

![create-gsm-fail](https://github.com/user-attachments/assets/ac6834bb-cd22-48c0-b89a-ceaaec8e1f63)

![system-journal](https://github.com/user-attachments/assets/dc9be946-1359-4d42-897b-8364e8c53ffb)

![snap-list](https://github.com/user-attachments/assets/4a9bd21f-c440-40c1-8f76-971cd47a5d0d)

**Comment by herosean** [comment]
looking forward for your reply,thanks

**Comment by herosean** [comment]
i try to remove the Network-manager 1.36.6 and reinstall network-manager 24/stable use command:
sudo snap install network-manager --channel=24/stable
the nmcli command work fine.
![snap-network-manager](https://github.com/user-attachments/assets/0d1bfb66-3318-40e0-8964-258456dae657)

**Comment by alfonsosanchezbeato** [comment]
It is recommended that you use the `network-manager` track that matches your UC version, the reason is that it needs to interact quite a bit with things like systemd-networkd and netplan which come from the base, so the sort of error you saw is not fully unexpected. Said this probably we should produce a warning when the nm track does not match the UC boot base.

**Comment by zub2** [comment]
I just faced the same issue on a Ubuntu 24.04.3 LTS laptop. Network Manager would work on existing connections, but trying to connect to a new WiFi network resulted in nothing happening when triggered from the GUI (i.e. I'd select the network in the list of found networks and... nothing, no error, no password popup). Trying to add the network via nmcli (`nmcli dev wifi connect network-ssid`) resulted in:
> Error: Failed to add/activate new connection: failure adding connection: keyfile writer produces an invalid connection: cannot access file: No such file or directory

Digging further (`journalctl -l -u snap.network-manager.networkmanager.service` showed:
> network-manager.networkmanager[27765]: Traceback (most recent call last):
network-manager.networkmanager[27765]:   File "/usr/sbin/netplan", line 20, in <module>
network-manager.networkmanager[27765]:     from netplan import Netplan
network-manager.networkmanager[27765]:   File "/usr/share/netplan/netplan/__init__.py", line 18, in <module>
network-manager.networkmanager[27765]:     from netplan.cli.core import Netplan
network-manager.networkmanager[27765]:   File "/usr/share/netplan/netplan/cli/core.py", line 24, in <module>
network-manager.networkmanager[27765]:     import netplan.cli.utils as utils
network-manager.networkmanager[27765]:   File "/usr/share/netplan/netplan/cli/utils.py", line 27, in <module>
network-manager.networkmanager[27765]:     import netplan.libnetplan as np
network-manager.networkmanager[27765]:   File "/usr/share/netplan/netplan/libnetplan.py", line 47, in <module>
network-manager.networkmanager[27765]:     lib = ctypes.CDLL(ctypes.util.find_library('netplan'))
network-manager.networkmanager[27765]:   File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
network-manager.networkmanager[27765]:     self._handle = _dlopen(self._name, mode)
network-manager.networkmanager[27765]: OSError: libnetplan.so.1: cannot open shared object file: No such file or directory
NetworkManager[882]: <error> [1764521465.2960] BUG: the profile cannot be stored in keyfile format without becoming unusable: cannot access file: No such file or directory
NetworkManager[882]: <info>  [1764521465.2961] audit: op="connection-add-activate" pid=27742 uid=0 result="fail" reason="failure adding connection: keyfile writer produces an invalid connection: cannot access file: No such file or directory"

Eventually I figured it's a netplan mismatch between, what I assume to be in the snap (the files referenced from the log above) and in the system. Then I was lucky to find this issue and I checked what channel of network-manager I had (`snap info --verbose network-manager`) - it was 1.36.6-15. I saw the channel 24/stable, which I assumed is what I should be using with Ubuntu 24.04, had 1.46.0-5. So I tried `snap refresh network-manager --channel 24/stable` and that fixed the issue.

I know this issue is closed, I'm adding the details in case someone else has the same issue as it wasn't that trivial to figure out.
